package com.roulette.report;

import java.util.List;

import com.roulette.model.Player;

/**
 * Class to create all reports necessary to print via console output.
 */
public class RouletteReport {

	/**
	 * Print via console output the report of players, showing either who won or lost.
	 *
	 * @param players list of players
	 * @param randomValue value generated by a random number
	 */
	public void print(final List<Player> players, final int randomValue) {

		System.out.println("\nNumber: " + randomValue);

		final String alignFormat = "| %-12s | %-8s | %-15s | %-8s |%n";

		System.out.format("+--------------+----------+-----------------+----------+%n");
		System.out.format("| Player       | Bet      |     Outcome     | Winnings |%n");
		System.out.format("+--------------+----------+-----------------+----------+%n");

		for (final Player player : players) {
			System.out.format(alignFormat,//
					player.getPlayerName(),//
					player.getBet(),//
					player.getOutcome(),//
					player.getWinnings());
		}

		System.out.format("+--------------+----------+-----------------+----------+%n");
	}
}